config/routes.rb
Rails.application.routes.draw do
  resources :films
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "search", to: "search#search"
  # Defines the root path route ("/")
  root "films#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    mapping do
      # ...
    end

    def self.search(query)
      # ...
    end
  end
end

app/models/film.rb
class Film < ApplicationRecord
  include Searchable

  searchkick

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: %w[title text]
          }
        },
        highlight: {
          pre_tags: ['<em>'],
          post_tags: ['</em>'],
          fields: {
            title: {},
            text: {}
          }
        }
      }
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: %i[show edit update destroy]

  # GET /films or /films.json
  def index
    @films = Film.all
  end

  # GET /films/1 or /films/1.json
  def show; end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit; end

  # POST /films or /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to film_url(@film), notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1 or /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to film_url(@film), notice: 'Film was successfully updated.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1 or /films/1.json
  def destroy
    @film.destroy

    respond_to do |format|
      format.html { redirect_to films_url, notice: 'Film was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_film
    @film = Film.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def film_params
    params.require(:film).permit(:budget, :description, :external_ids, :length, :movie_type, :premiere_bluray, :premiere_digital, :premiere_dvd, :premiere_world, :rating, :rating_age_limits, :rating_mpaa, :remote_images, :slogan, :slug, :source, :source_lang, :title, :year)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:term].nil?
      @films = []
    else
      term = params[:term]
      @films = Film.search term, fields: [:text], highlight: true
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/films/_film.html.erb
<div id="<%= dom_id film %>">
  <p>
    <strong>Budget:</strong>
    <%= film.budget %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= film.description %>
  </p>

  <p>
    <strong>External ids:</strong>
    <%= film.external_ids %>
  </p>

  <p>
    <strong>Length:</strong>
    <%= film.length %>
  </p>

  <p>
    <strong>Movie type:</strong>
    <%= film.movie_type %>
  </p>

  <p>
    <strong>Premiere bluray:</strong>
    <%= film.premiere_bluray %>
  </p>

  <p>
    <strong>Premiere digital:</strong>
    <%= film.premiere_digital %>
  </p>

  <p>
    <strong>Premiere dvd:</strong>
    <%= film.premiere_dvd %>
  </p>

  <p>
    <strong>Premiere world:</strong>
    <%= film.premiere_world %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= film.rating %>
  </p>

  <p>
    <strong>Rating age limits:</strong>
    <%= film.rating_age_limits %>
  </p>

  <p>
    <strong>Rating mpaa:</strong>
    <%= film.rating_mpaa %>
  </p>

  <p>
    <strong>Remote images:</strong>
    <%= film.remote_images %>
  </p>

  <p>
    <strong>Slogan:</strong>
    <%= film.slogan %>
  </p>

  <p>
    <strong>Slug:</strong>
    <%= film.slug %>
  </p>

  <p>
    <strong>Source:</strong>
    <%= film.source %>
  </p>

  <p>
    <strong>Source lang:</strong>
    <%= film.source_lang %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= film.title %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= film.year %>
  </p>

</div>

app/views/films/_form.html.erb
<%= form_with(model: film) do |form| %>
  <% if film.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
        <% film.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :budget, style: "display: block" %>
    <%= form.text_field :budget %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :external_ids, style: "display: block" %>
    <%= form.text_field :external_ids %>
  </div>

  <div>
    <%= form.label :length, style: "display: block" %>
    <%= form.text_field :length %>
  </div>

  <div>
    <%= form.label :movie_type, style: "display: block" %>
    <%= form.text_field :movie_type %>
  </div>

  <div>
    <%= form.label :premiere_bluray, style: "display: block" %>
    <%= form.date_field :premiere_bluray %>
  </div>

  <div>
    <%= form.label :premiere_digital, style: "display: block" %>
    <%= form.date_field :premiere_digital %>
  </div>

  <div>
    <%= form.label :premiere_dvd, style: "display: block" %>
    <%= form.date_field :premiere_dvd %>
  </div>

  <div>
    <%= form.label :premiere_world, style: "display: block" %>
    <%= form.date_field :premiere_world %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.text_field :rating %>
  </div>

  <div>
    <%= form.label :rating_age_limits, style: "display: block" %>
    <%= form.number_field :rating_age_limits %>
  </div>

  <div>
    <%= form.label :rating_mpaa, style: "display: block" %>
    <%= form.text_field :rating_mpaa %>
  </div>

  <div>
    <%= form.label :remote_images, style: "display: block" %>
    <%= form.text_field :remote_images %>
  </div>

  <div>
    <%= form.label :slogan, style: "display: block" %>
    <%= form.text_field :slogan %>
  </div>

  <div>
    <%= form.label :slug, style: "display: block" %>
    <%= form.text_field :slug %>
  </div>

  <div>
    <%= form.label :source, style: "display: block" %>
    <%= form.text_field :source %>
  </div>

  <div>
    <%= form.label :source_lang, style: "display: block" %>
    <%= form.text_field :source_lang %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/films/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
    <%= link_to 'SearchFlix', 
    root_path, class:"navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/films/new">Add Film</a>
          </li>
        </ul>
        <%= render 'search/form' %>
      </div>
      
    </div>
  </nav>

app/views/films/edit.html.erb
<h1>Editing film</h1>

<%= render "form", film: @film %>

<br>

<div>
  <%= link_to "Show this film", @film %> |
  <%= link_to "Back to films", films_path %>
</div>

app/views/films/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Films</h1>

<div id="films">
  <% @films.each do |film| %>
    <%= render film %>
    <p>
      <%= link_to "Show this film", film %>
    </p>
  <% end %>
</div>

<%= link_to "New film", new_film_path %>

app/views/films/new.html.erb
<h1>New film</h1>

<%= render "form", film: @film %>

<br>

<div>
  <%= link_to "Back to films", films_path %>
</div>

app/views/films/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @film %>

<div>
  <%= link_to "Edit this film", edit_film_path(@film) %> |
  <%= link_to "Back to films", films_path %>

  <%= button_to "Destroy this film", @film, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchFlix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'films/header' %>
    <div class="container">
      <br/>
      <%= yield %>
    </div>
  </body>
</html>

app/views/search/_form.html.erb
<%= form_for :term, url: search_path, method: :get, class: "d-flex" do |form| %>
  <p>
    <%= text_field_tag :term, params[:term], class: "form-control me-2" %>
  </p>
    &nbsp
  <p>
    <%= submit_tag "Search", name: nil, class: "btn btn-outline-success" %>
  </p>
<% end %>

app/views/search/search.html.erb
<h2>Search Results for: <i><%= params[:term] %></i></h2>
 
<% if @films %>
<ul class="search_results">
  <% @films.with_details.each do |film, details| %>
    <li>
      <h3>
        <%= link_to film.title, controller: "films", action: "show", id: film.id %>
      </h3>
      <p><%= details[:highlight][:text].html_safe %>...</p>
    </li>
  <% end %>
</ul>
<% else %>
  <p>Your search did not match any documents.</p>
<% end %>